// Code generated by errgen. DO NOT EDIT.
package example

import (
	"errors"
	"fmt"
	"strconv"
)

type WithAnonError struct {
	reasonErrGen string
	errErrGen    error
}

func NewWithAnonError(reasonErrGen string, errErrGen error) *WithAnonError {
	return &WithAnonError{
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *WithAnonError) Error() string {
	return "[" + "example" + "] - " +
		"WithAnon - " + e.reasonErrGen +
		"\n" +
		e.errErrGen.Error()
}

func (e *WithAnonError) Unwrap() error {
	return e.errErrGen
}

func (e *WithAnonError) Is(target error) bool {
	if _, ok := target.(*WithAnonError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type WithAnon_2Error struct {
	reasonErrGen string
	errErrGen    error
}

func NewWithAnon_2Error(reasonErrGen string, errErrGen error) *WithAnon_2Error {
	return &WithAnon_2Error{
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *WithAnon_2Error) Error() string {
	return "[" + "example" + "] - " +
		"WithAnon_2 - " + e.reasonErrGen +
		"\n" +
		e.errErrGen.Error()
}

func (e *WithAnon_2Error) Unwrap() error {
	return e.errErrGen
}

func (e *WithAnon_2Error) Is(target error) bool {
	if _, ok := target.(*WithAnon_2Error); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type WithAnon_3Error struct {
	reasonErrGen string
	errErrGen    error
}

func NewWithAnon_3Error(reasonErrGen string, errErrGen error) *WithAnon_3Error {
	return &WithAnon_3Error{
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *WithAnon_3Error) Error() string {
	return "[" + "example" + "] - " +
		"WithAnon_3 - " + e.reasonErrGen +
		"\n" +
		e.errErrGen.Error()
}

func (e *WithAnon_3Error) Unwrap() error {
	return e.errErrGen
}

func (e *WithAnon_3Error) Is(target error) bool {
	if _, ok := target.(*WithAnon_3Error); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type MarshalError struct {
	reasonErrGen string
	errErrGen    error
}

func NewMarshalError(reasonErrGen string, errErrGen error) *MarshalError {
	return &MarshalError{
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *MarshalError) Error() string {
	return "[" + "example" + "] - " +
		"Marshal - " + e.reasonErrGen +
		"\n" +
		e.errErrGen.Error()
}

func (e *MarshalError) Unwrap() error {
	return e.errErrGen
}

func (e *MarshalError) Is(target error) bool {
	if _, ok := target.(*MarshalError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type UpdateNameError struct {
	newName      string
	reasonErrGen string
	errErrGen    error
}

func NewUpdateNameError(newName string, reasonErrGen string, errErrGen error) *UpdateNameError {
	return &UpdateNameError{
		newName:      newName,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *UpdateNameError) Error() string {
	return "[" + "example" + ".User" + "] - " +
		"UpdateName - " + e.reasonErrGen +
		" - args: {" +
		"newName: " + e.newName +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *UpdateNameError) Unwrap() error {
	return e.errErrGen
}

func (e *UpdateNameError) Is(target error) bool {
	if _, ok := target.(*UpdateNameError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type ProcessUserError struct {
	user         *User
	count        int
	reasonErrGen string
	errErrGen    error
}

func NewProcessUserError(user *User, count int, reasonErrGen string, errErrGen error) *ProcessUserError {
	return &ProcessUserError{
		user:         user,
		count:        count,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *ProcessUserError) Error() string {
	return "[" + "example" + "] - " +
		"ProcessUser - " + e.reasonErrGen +
		" - args: {" +
		"user: " + fmt.Sprintf("%#v", e.user) + ", " +
		"count: " + strconv.Itoa(e.count) +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *ProcessUserError) Unwrap() error {
	return e.errErrGen
}

func (e *ProcessUserError) Is(target error) bool {
	if _, ok := target.(*ProcessUserError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type IsOlderError struct {
	user         *User
	count        int
	reasonErrGen string
	errErrGen    error
}

func NewIsOlderError(user *User, count int, reasonErrGen string, errErrGen error) *IsOlderError {
	return &IsOlderError{
		user:         user,
		count:        count,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *IsOlderError) Error() string {
	return "[" + "example" + ".User" + "] - " +
		"IsOlder - " + e.reasonErrGen +
		" - args: {" +
		"user: " + fmt.Sprintf("%#v", e.user) + ", " +
		"count: " + strconv.Itoa(e.count) +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *IsOlderError) Unwrap() error {
	return e.errErrGen
}

func (e *IsOlderError) Is(target error) bool {
	if _, ok := target.(*IsOlderError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type IsYoungerError struct {
	user         *User
	count        int
	reasonErrGen string
	errErrGen    error
}

func NewIsYoungerError(user *User, count int, reasonErrGen string, errErrGen error) *IsYoungerError {
	return &IsYoungerError{
		user:         user,
		count:        count,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *IsYoungerError) Error() string {
	return "[" + "example" + ".User" + "] - " +
		"IsYounger - " + e.reasonErrGen +
		" - args: {" +
		"user: " + fmt.Sprintf("%#v", e.user) + ", " +
		"count: " + strconv.Itoa(e.count) +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *IsYoungerError) Unwrap() error {
	return e.errErrGen
}

func (e *IsYoungerError) Is(target error) bool {
	if _, ok := target.(*IsYoungerError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type IsYoungerOrOlderError struct {
	user         *User
	count        int
	reasonErrGen string
	errErrGen    error
}

func NewIsYoungerOrOlderError(user *User, count int, reasonErrGen string, errErrGen error) *IsYoungerOrOlderError {
	return &IsYoungerOrOlderError{
		user:         user,
		count:        count,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *IsYoungerOrOlderError) Error() string {
	return "[" + "example" + ".User" + "] - " +
		"IsYoungerOrOlder - " + e.reasonErrGen +
		" - args: {" +
		"user: " + fmt.Sprintf("%#v", e.user) + ", " +
		"count: " + strconv.Itoa(e.count) +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *IsYoungerOrOlderError) Unwrap() error {
	return e.errErrGen
}

func (e *IsYoungerOrOlderError) Is(target error) bool {
	if _, ok := target.(*IsYoungerOrOlderError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type FindNameError struct {
	name         string
	reasonErrGen string
	errErrGen    error
}

func NewFindNameError(name string, reasonErrGen string, errErrGen error) *FindNameError {
	return &FindNameError{
		name:         name,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *FindNameError) Error() string {
	return "[" + "example" + ".User" + "] - " +
		"FindName - " + e.reasonErrGen +
		" - args: {" +
		"name: " + e.name +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *FindNameError) Unwrap() error {
	return e.errErrGen
}

func (e *FindNameError) Is(target error) bool {
	if _, ok := target.(*FindNameError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type LockError struct {
	name         string
	reasonErrGen string
	errErrGen    error
}

func NewLockError(name string, reasonErrGen string, errErrGen error) *LockError {
	return &LockError{
		name:         name,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *LockError) Error() string {
	return "[" + "example" + ".User" + "] - " +
		"Lock - " + e.reasonErrGen +
		" - args: {" +
		"name: " + e.name +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *LockError) Unwrap() error {
	return e.errErrGen
}

func (e *LockError) Is(target error) bool {
	if _, ok := target.(*LockError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}

type CheckConfigError struct {
	nothing      any
	reasonErrGen string
	errErrGen    error
}

func NewCheckConfigError(nothing any, reasonErrGen string, errErrGen error) *CheckConfigError {
	return &CheckConfigError{
		nothing:      nothing,
		reasonErrGen: reasonErrGen,
		errErrGen:    errErrGen,
	}
}

func (e *CheckConfigError) Error() string {
	return "[" + "example" + ".User" + "] - " +
		"CheckConfig - " + e.reasonErrGen +
		" - args: {" +
		"nothing: " + fmt.Sprintf("%#v", e.nothing) +
		"}" + "\n" +
		e.errErrGen.Error()
}

func (e *CheckConfigError) Unwrap() error {
	return e.errErrGen
}

func (e *CheckConfigError) Is(target error) bool {
	if _, ok := target.(*CheckConfigError); ok {
		return true
	}
	return errors.Is(e.errErrGen, target)
}
